[project]
name = "assignment-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "byllm>=0.4.2",
    "jac-cloud>=0.2.7",
    "jaclang>=0.8.7",
    "pygame>=2.6.1",
    "rich>=14.1.0",
]
